apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app # This is the app as declared in the deployment.
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000 # This is the target port, the same env var $PORT in Dockerfile, now that it is not overriden by envvar.yaml